bus:
  device: can0
  baudrate: 500K

sync:
  interval_ms: 10
  overflow: 0

nodes:
  theta2:
    id: 1
    eds_pkg: iwp_bringup # optionals package  name for relative path
    eds_file: "config/epos7010-20211018-2.dcf"
    # dcf_overlay:
      # "6060" : "-3"
    # publish: ["1003sub0!"]
    # eds_file: "config/maxon_motor_EPOS2_2126h_6420h_0000h_0000h.eds"

defaults: # optional, all defaults can be overwritten per node
  # canopen_chain_node settings ..
  motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
  motor_layer: # settings passed to motor layer (plugin-specific)
    switching_state: 5 # (Operation_Enable), state for mode switching
  pos_to_device: "rint(rad2deg(pos)*1000)" # rad -> mdeg
  pos_from_device: "deg2rad(obj6064)/1000" # actual position [mdeg] -> rad
  vel_to_device: "rint(rad2deg(vel)*1000)" # rad/s -> mdeg/s
  vel_from_device: "deg2rad(obj606C)/1000" # actual velocity [mdeg/s] -> rad/s
  eff_to_device: "rint(eff)" # just round to integer
  eff_from_device: "0" # unset
  