# Publish all joint states -----------------------------------
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

theta2_controller:
  type: "effort_controllers/JointEffortController"
  joint: "theta2"
  required_drive_mode: 4
